### ISSUE TITLE
Config Issues

### ISSUE THREAD

**Issue by aptonline** [Sanderhuisman/docker_monitor#20]
Hi, Just installed `Docker_Monitor` via HACS after adding it as a customer integration but having issues setting up as HA is complaining of config errors, the docs don't seem very clear.  I have used a docker proxy (`Tecnativa/docker-socket-proxy`) which seems to be working ok.  Here is my config:

```
docker_monitor:
  url: 192.168.1.12:2375
  containers:
 
  monitored_conditions:
    - utilization_version
    - container_status
    - container_memory_usage
    - container_memory_percentage_usage
    - container_cpu_percentage_usage
```

I also tried with `hosts:` (after seeing an issue post) but I think this is a `dev` config option and not the release.  Any help would be useful.
