### ISSUE TITLE
Invalid option URL??

### ISSUE THREAD

**Issue by aptonline** [Sanderhuisman/docker_monitor#23]
Had docker monitor working perfectly until recent update and now it complains that URL is an invalid option:

`Invalid config for [docker_monitor]: [url] is an invalid option for [docker_monitor]. Check: docker_monitor->docker_monitor->url. (See /config/configuration.yaml, line 252). Please check the docs at https://home-assistant.io/components/docker_monitor/`

I couldn’t see any breaking changes. This is my config:

```
docker_monitor:
  url: tcp://192.168.1.12:2375
  containers:
    - homeassistant
    - toke-mosquitto1
    - ESPHome
    …
```

**Comment by aptonline** [comment]
Any update on this?

**Comment by aptonline** [comment]
I have downgraded to `0.0.4 `which has resolved the issue.
Any update on a fix?

**Comment by hummelriegel** [comment]
I have the same issues, and it seems that you have to use the configurations mentioned in the development-branch now: https://github.com/Sanderhuisman/docker_monitor/tree/develop

Took me some time to figure this out, since I installed the current version with HACS. I think HACS also has options for beta-releases as well.

Following the manual of the development branch, I changed my configuration to the following:
```
docker_monitor:
  hosts:
    - name: Docker
      url: unix://var/run/docker.sock
```
I still have some difficulties with the containers, though. It seems like one has to add them explicitely at the moment, which I did according to the manual as well:
```
docker_monitor:
  hosts:
    - name: Docker
      url: unix://var/run/docker.sock
      containers:
        home-assistant:
          switch: False
          sensors:
            - status
            - uptime
            - cpu_percentage_usage
            - memory_usage
            - memory_percentage_usage
            - network_total_up
            - network_total_down
        zigbee2mqtt:
          switch: False
          sensors:
            - status
            - uptime
            - cpu_percentage_usage
            - memory_usage
            - memory_percentage_usage
            - network_total_up
            - network_total_down
```

Sensors do not exactly match the names in the config. For the home-assistant container I use the following lovelace card:
```type: entities
entities:
  - entity: sensor.docker_home_assistant_cpu_use
  - entity: sensor.docker_home_assistant_memory_use
  - entity: sensor.docker_home_assistant_memory_use_percent
  - entity: sensor.docker_home_assistant_up_time
  - entity: sensor.docker_home_assistant_network_total_up
  - entity: sensor.docker_home_assistant_network_total_down
title: Docker Containers
show_header_toggle: false```
